FROM ruby:3.4.10

ARG UID=1000
ARG GID=1000

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      libpq-dev \
      libyaml-dev \
      postgresql-client \
      curl && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -g ${GID} app && \
    useradd -m -u ${UID} -g ${GID} -s /bin/bash app

WORKDIR /rails

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

RUN chown -R app:app /rails

USER app

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]